### ISSUE TITLE
sum.js

### ISSUE THREAD

**Issue by azole** [YawenChan/hello-node#1]
如果要在 sum 函式裡直接 console.log 答案的話，那外部在呼叫 sum 的時候，就不需要加上 console.log ，例如以下這幾行：

```javascript
console.log(sum(2));
console.log(sum(6));
console.log(sum(10));
```
因為 sum 函式本身是沒有回傳值的，這裡寫 console.log 的話就會顯示 undefined 喔

**Comment by MikaChan602** [comment]
謝謝老師，已修正上傳至github。
